### PR TITLE
Validate binary

### PR DESCRIPTION
**Pull request by outscale-vbr**
* verify and install kubectl, clusterctl, controller-gen, mockgen, envsubst, testenv, helm, kind, kustomize, packer

### CODE REVIEW

**Comment by outscale-mdr** [comment]
What is the use ? For new dev on the project ?

**Review by outscale-mdr — COMMENTED** [review]
What is the use ? For new dev on the project ? If so, can you upgrade the doc ?

**Comment by outscale-vbr** [comment]
@outscale-mdr @outscale-hmi 
To validate and install binary.

**Review by outscale-mdr — APPROVED** [review]

**Review by outscale-hmi — COMMENTED** [review]
ok for me

**Comment by outscale-vbr** [comment]
close https://github.com/outscale-dev/cluster-api-provider-outscale/issues/47

**Comment by outscale-vbr** [comment]
close https://github.com/outscale-dev/cluster-api-provider-outscale/issues/47

**Pull request merged**
