### PR TITLE
Change verbosity

### PR DESCRIPTION
**Pull request by outscale-vbr**
**What type of PR is this?**
/kind cleanup    

**What this PR does / why we need it**:
Change verbosity.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/outscale-dev/cluster-api-provider-outscale/issues/108

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Comment by outscale-vbr** [comment]
Closes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/108

**Comment by outscale-hmi** [comment]
Need to clean the PR, some commits are not for the verbosity

**Comment by outscale-vbr** [comment]
Ok done

**Comment by outscale-vbr** [comment]
@outscale-hmi @outscale-mdr Are you ok with the latest version ?

**Review by outscale-mdr — APPROVED** [review]
Ok for the objective of this PR, but we should schedule to rework on the logs, they are too many and some could have more meaning than just describing (see the two previous comments)

**Pull request merged**
