### PR TITLE
Add shellcheck, yamllint and boilerplate

### PR DESCRIPTION
**Pull request by outscale-vbr**
**What type of PR is this?**
/kind feature  

**What this PR does / why we need it**:
Add lint yaml, shellcheck, boilerplate
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
We migrate to another region and test is fix only in https://github.com/outscale-dev/cluster-api-provider-outscale/pull/105
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Review by outscale-hmi — COMMENTED** [review]
OK

**Comment by outscale-vbr** [comment]
close https://github.com/outscale-dev/cluster-api-provider-outscale/issues/46

**Review by outscale-mdr — APPROVED** [review]
OK, next time, split between when you add the tools and when you apply them and add its modifications

**Comment by outscale-vbr** [comment]
Closes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/46

**Pull request merged**
