### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by outscale-vbr**

### CODE REVIEW

**Comment by outscale-vbr** [comment]
Close https://github.com/outscale-dev/cluster-api-provider-outscale/issues/7

**Comment by outscale-vbr** [comment]
Close https://github.com/outscale-dev/cluster-api-provider-outscale/issues/7

**Comment by outscale-mdr** [comment]
Take a look at [Issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Comment by outscale-mdr** [comment]
Other than that, **ok**

**Review by jerome-jutteau — APPROVED** [review]

**Comment by outscale-vbr** [comment]
@outscale-mdr I change the format base on your comment.

**Review by outscale-mdr — APPROVED** [review]

**Review by jerome-jutteau — APPROVED** [review]

**Pull request merged**
